### ISSUE TITLE
Add Support for Configuration File in jacoco-filter

### ISSUE THREAD

**Issue by miroslavpojer** [MoranaApps/jacoco-filter#19]
### Current State
The `jacoco-filter` tool currently requires all parameters to be provided via the command line. Key arguments include:

- `--inputs` / `--input-paths`: Explicit paths to `jacoco.xml` files, directories, or glob patterns.
- `--rules`: Path to the filtering rules file.
- `--exclude-paths`: Paths or patterns to exclude from input search.

While this CLI-driven approach offers flexibility, it becomes unwieldy and error-prone for complex workflows or repeated executions using the same settings.

---

### Proposed Enhancement

Introduce support for loading parameters from a **configuration file**.

#### 1. Configuration File Support
- **Format:** Preferably **YAML** (or optionally JSON, given it's already used in output reports) for readability and structured config management.
- **Supported Parameters:** The configuration file should mirror the current CLI arguments. For example:
  - `input_paths` → `--inputs` / `--input-paths`
  - `exclude_paths` → `--exclude-paths`
  - `rules` → `--rules`

#### 2. Priority Handling – CLI Overrides Config File
- CLI arguments should always **override** the corresponding values from the config file.
- Example: If `output_dir` is set to `target/filtered/` in `config.yaml`, but the CLI includes `--output temp-filtered/`, the tool should use `temp-filtered/`.

---

### Benefits

- **Simplified Configuration:** Reduces clutter in CI/CD scripts and helps maintain reusable setups.
- **Improved Integration:** Easier integration into SBT, Maven, and GitHub Workflows.
- **Better Transparency:** A centralized config improves readability and documents all tool options in one place.

---

### Roadmap Placement

This feature aligns with **Stage 3: Full Integration and Robust Reporting (v1.2.0)**. It directly supports goals such as:

- Custom SBT task implementation
- exec-maven-plugin customization
- Building `.github/workflows/coverage-filter.yml`

---

#### Affected Modules

- `cli.py`: Add a new optional argument `--config <path_to_file>` to accept the config path.
- `main.py`: Responsible for loading and merging CLI arguments and config file content.
- New utility/helper: For parsing YAML/JSON (e.g., using `PyYAML` or `json`), and merging logic.

---

### Example Configuration File (config.yaml)

```yaml
input_paths:
  - "target/jacoco-report/**/*.xml"
  - "another/path/report.xml"
exclude_paths:
  - "target/jacoco-report/excluded_module/"
rules: "rules/rules.txt"
output_dir: "target/jacoco-filtered/"
report_json: "impact-report.json"
report_csv: "impact-report.csv"
```
